<?php
/** @var \Elgentos\ReorderAlternatives\Block\Alternatives $block */
$nonSalableProducts = $block->getNonSalableProducts();
$salableProducts = $block->getSalableProducts();
$alternativeProducts = $block->getAlternativeProducts();
?>

<?php if($alternativeProducts): ?>
    <form action="<?php echo $block->getUrl('sales/order/alternativereorder') ?>" method="post">
        <?php foreach($salableProducts as $salableProductId): ?>
        <input type="hidden" name="product[<?=$salableProductId;?>-<?=$salableProductId;?>]" value="<?=$salableProductId;?>" />
        <?php endforeach; ?>
        <?php echo $block->getBlockHtml('formkey'); ?>
        <?php foreach ($nonSalableProducts as $nonSalableProduct): ?>
            <?php if (isset($alternativeProducts[$nonSalableProduct->getId()])): ?>
                <p class="py-2"><?=__('Unfortunately the product %1 is not available anymore.', $nonSalableProduct->getName()); ?></p>
                <p class="py-2"><?=__('Please select an alternative for %1 (SKU %2).', $nonSalableProduct->getName(), $nonSalableProduct->getSku());?></p>
                <ul class="py-2">
                    <?php foreach ($alternativeProducts[$nonSalableProduct->getId()] as $product): ?>
                        <li class="py-2">
                            <input type="checkbox" class="mr-2" name="product[<?= $nonSalableProduct->getId() . '-' . $product->getId() ?>]" id="product-<?= $nonSalableProduct->getId() . '-' . $product->getId() ?>" value="<?= $nonSalableProduct->getId() . '-' . $product->getId() ?>">
                            <label for="product-<?= $nonSalableProduct->getId() . '-' . $product->getId() ?>"><?= $product->getName() ?> (SKU <?= $product->getSku(); ?>)</label>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php else: ?>
                <p><?=__('No alternative products available for this product.');?></p>
            <?php endif; ?>
        <?php endforeach; ?>
        <button type="submit" class="p-2 bg-green-100"><?=__('Reorder now');?></button>
    </form>
<?php else: ?>
    <p><?=__('No alternative products available, reordering is not possible.');?></p>
<?php endif; ?>
